# #####################################################################
# Automatically generated by qmake (2.01a) Sat Jun 6 02:49:48 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    blog \
    images \
    MainWindow \
    twitlib \
    Ui
INCLUDEPATH += . \
    MainWindow \
    twitlib

# Input
HEADERS += blog.h \
    derivedconfigdialog.h \
    lineedit.h \
    loginDerived.h \
    mainWindowDerived.h \
    sendTwitDerived.h \
    styleSheet.h \
    twitterbackendinterface.h \
    blog/blog.h \
    MainWindow/mainwindowimpl.h \
    twitlib/Core.h \
    twitlib/Decipher.h \
    twitlib/ITwitReply.h \
    twitlib/QTwitLib.h \
    twitlib/Returnables.h \
    twitlib/Server.h \
    ../Users/vikasachi/Desktop/tagger/explorer/ui_explorer.h \
    ../Users/vikasachi/Desktop/tagger/explorer/ui_browseFolder.h \
    ../Users/vikasachi/Desktop/tagger/explorer/tageditor.h \
    ../Users/vikasachi/Desktop/tagger/explorer/explorer.h \
    ../Users/vikasachi/Desktop/tagger/explorer/browsefolder.h \
    ../Users/vikasachi/Desktop/tagger/server/server.h \
    ../Users/vikasachi/Desktop/tagger/includes/strfunc.h \
    ../Users/vikasachi/Desktop/tagger/includes/stopwatch.h \
    ../Users/vikasachi/Desktop/tagger/includes/sharedseg.h \
    ../Users/vikasachi/Desktop/tagger/includes/sharedseg.h~ \
    ../Users/vikasachi/Desktop/tagger/includes/getabsmod.h \
    ../Users/vikasachi/Desktop/tagger/includes/tagdefs.h \
    ../Users/vikasachi/Desktop/tagger/includes/fileperm.h \
    ../Users/vikasachi/Desktop/tagger/includes/history.h \
    ../Users/vikasachi/Desktop/tagger/includes/client.h \
    ../Users/vikasachi/Desktop/tagger/includes/linkedlist.h~ \
    ../Users/vikasachi/Desktop/tagger/includes/linkedlist.h \
    ../Users/vikasachi/Desktop/tagger/includes/nPatriciaTrie.h~ \
    ../Users/vikasachi/Desktop/tagger/includes/nPatriciaTrie.h \
    menuTagEXPLORE.h \
    ui_tageditor.h
FORMS += Ui/config.ui \
    Ui/imageBrowser.ui \
    Ui/login.ui \
    Ui/mainWindow.ui \
    Ui/sendTwit.ui \
    ../Users/vikasachi/Desktop/tagger/explorer/explorer.ui \
    ../Users/vikasachi/Desktop/tagger/explorer/browseFolder.ui \
    ../Users/vikasachi/Desktop/tagger/tageditor/tageditor.ui \
    Ui/sendTwit.ui \
    Ui/mainWindow.ui \
    Ui/login.ui \
    Ui/imageBrowser.ui \
    Ui/config.ui
SOURCES += derivedconfigdialog.cpp \
    lineedit.cpp \
    loginDerived.cpp \
    main.cpp \
    mainWindowDerived.cpp \
    sendTwitDerived.cpp \
    twitterbackendinterface.cpp \
    MainWindow/mainwindowimpl.cpp \
    twitlib/Core.cpp \
    twitlib/Decipher.cpp \
    twitlib/QTwitLib.cpp \
    ../Users/vikasachi/Desktop/tagger/explorer/tageditor.cpp \
    ../Users/vikasachi/Desktop/tagger/explorer/explorer.cpp \
    ../Users/vikasachi/Desktop/tagger/explorer/browsefolder.cpp \
    ../Users/vikasachi/Desktop/tagger/common/client.cpp \
    ../Users/vikasachi/Desktop/tagger/server/server.c \
    menuTagEXPLORE.cpp
RESOURCES += images/images.qrc \
    ../Users/vikasachi/Documents/Downloads/New \
    Folder/icons.qrc
QT += network \
    xml
OTHER_FILES += 
